{% set name = "mangum" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mangum-{{ version }}.tar.gz
  sha256: 50179395012d9ae3df30484c16280decf0c56fb4c76bd6e1979b9b60135f254f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
  run:
    - python >=3.7
    - typing-extensions

test:
  imports:
    - mangum
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jordaneremieff/mangum
  summary: AWS Lambda support for ASGI applications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
