{% set name = "mangum" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mangum-{{ version }}.tar.gz
  sha256: 0050447b60d832dcc45cc9d917c9e0f4e9174e2d9630f621d567510d51d286bd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - mangum
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jordaneremieff/mangum
  summary: AWS Lambda support for ASGI applications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
