{% set name = "mangum" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mangum-{{ version }}.tar.gz
  sha256: e388e7c491b7b67970f8234e46fd4a7b21ff87785848f418de08148f71cf0bd6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - mangum
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jordaneremieff/mangum
  summary: AWS Lambda support for ASGI applications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
