schema_version: 1

context:
  name: mangum
  version: "0.21.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mangum-${{ version }}.tar.gz
  sha256: e31ed72d67f9958fa4379f65df77729906dec6dfa00afa6ed4e06c77833000de

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
  run:
    - python >=${{ python_min }}
    - typing-extensions

tests:
  - python:
      imports:
        - mangum
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: AWS Lambda support for ASGI applications
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/jordaneremieff/mangum

extra:
  recipe-maintainers:
    - thewchan
